# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.0381, 0.9480, 0.5069, 0.4428, 0.7878, 0.9312, 0.2312],
        [0.2903, 0.2459, 0.1483, 0.4979, 0.5210, 0.8485, 0.3742],
        [0.3743, 0.4696, 0.2210, 0.4532, 0.9034, 0.9197, 0.4869],
        [0.7918, 0.5261, 0.6918, 0.2800, 0.3514, 0.0822, 0.5407],
        [0.9615, 0.4898, 0.6365, 0.0762, 0.3533, 0.9798, 0.4537],
        [0.1622, 0.0533, 0.2075, 0.6961, 0.8656, 0.7742, 0.0114],
        [0.0326, 0.5084, 0.1507, 0.5061, 0.0377, 0.4494, 0.5400]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
random_tensor_2 = torch.rand(1,7)

# Perform matrix multiplication
mat_mul_tensor = torch.matmul(random_tensor, random_tensor_2.T)
mat_mul_tensor

tensor([[2.2798],
        [1.4465],
        [2.0452],
        [1.5638],
        [1.5759],
        [1.4823],
        [1.2401]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
# Create two random tensors
random_tensor = torch.rand(7,7)
random_tensor

random_tensor_2 = torch.rand(1,7)

# Matrix multiply tensors
mat_mul_tensor = torch.matmul(random_tensor, random_tensor_2.T)
mat_mul_tensor, mat_mul_tensor.size()

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
"cuda" if torch.cuda.is_available() else "cpu"

'cuda'

In [14]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed_all(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)
random_tensor3 = torch.rand(2,3)
random_tensor3_gpu = random_tensor3.to(device)
print(random_tensor3_gpu)

random_tensor4 = torch.rand(2,3)
random_tensor4_gpu = random_tensor4.to(device)
print(random_tensor4_gpu)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [23]:
# Perform matmul on tensor_A and tensor_B

torch_mat_mul = torch.matmul(random_tensor3_gpu, random_tensor4_gpu.T)
torch_mat_mul, torch_mat_mul.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [53]:
# Find max
print(f"The maximum value of the previous tensor is {torch_mat_mul.max()}")
# Find min
print(f"The minimum value of the previous tensor is {torch_mat_mul.min()}")

The maximum value of the previous tensor is 0.5617256760597229
The minimum value of the previous tensor is 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [31]:
# Find arg max
x = torch_mat_mul.argmax()
print(x)
# Find arg min
x = torch_mat_mul.argmin()
print(x)

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [54]:
# Set seed
RANDOM_SEED = 7

torch.manual_seed(RANDOM_SEED)
# Create random tensor
x = torch.rand(1,1,1,10)
print(f"The first tensor is, {x}, and shape {x.shape}")
# Remove single dimensions
print(f"The second tensor is {x.squeeze()}, and shape {x.squeeze().shape}")

# Print out tensors and their shapes


The first tensor is, tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), and shape torch.Size([1, 1, 1, 10])
The second tensor is tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), and shape torch.Size([10])
